title: AnorakDev
author: AnorakX
url: ''
description: >
  AnorakX#8873 is a Discord.py developer who has been coding in Python since 2019 and started using Discord.py 
  when the pandemic began. He has since created many different kinds of bots and is continuing to explore. He uses Discord.py, 
  numerous pip modules, and MongoDB in his projects.
permalink: '/:slug.html'
favicon: ./logo.png
remote_theme: abhinavs/moonwalk
theme_config:
  appearance: dark
  back_home_text: home..
  date_format: '%Y-%m-%d'
  show_description: true
  show_navbar: true
  show_footer: true
  show_projects: true
  show_old_projects: true
  show_misc_list: false
  show_soopr: true
  soopr_base_url: 'https://soopr.netlify.app'
highlighter: rouge
sass:
  style: ':compressed'
plugins:
  - jekyll-feed
  - jekyll-seo-tag
baseurl: ''
